### ISSUE TITLE
Additions to FAQ

### ISSUE THREAD

**Issue by tserenam** [ethereum/fellowship-program-website#20]
@gichiba I'm sure there is a proper way to raise this issue but please can you help to add these questions to the FAQ page in whichever order/wherever it makes most sense?

Thank youuu

**I live in [insert country] am I eligible?**
To reach the next billion, we must overcome many gaps in representation across cultures, nationalities, and economic classes. Yes! we are looking for Fellows everywhere :)

**Are applicants supposed to be working in a specific domain to qualify as a Fellow?** 
Applicants from all domains are eligible. We want to hear from you - what are the most pertaining needs but also the barriers to entry for underrepresented people and communities to ethereum and web3. We are looking for applications from the community showcasing Ethereum as a [public good](link to public good FAQ)*.

**I am building on L2, should I apply?**
Yes! Layer 2s are eligible. 

**What is the structure of the program? How will you ensure that we will succeed?**
This Fellowship is a self-driven and self-directed program, meaning that Fellows should define their own project goals and drive it forward in a measurable way during the 6 month program.

The Ethereum Foundation supports Fellows during the 6 month program by providing:

- Networking and community-building
- Guidance
- Mentorship
- Potential funding
- Exposure

**What is a public good?**
[The full definition of a public good is complicated](https://en.wikipedia.org/wiki/Public_good_(economics)). But in the context of Ethereum and the Fellowship Program, we can say that public goods solve a problem or benefit a community by providing value that can be used by anyone, and that can be reproduced/replicated in a wide variety of places/contexts.

**Comment by gichiba** [comment]
Thanks for putting this as an issue! This is the proper way!

**Comment by gichiba** [comment]
So in the PR above I didn't do a few things: 

"I live in [insert country]" is a thorny question, because we can't accept applications from countries with US sanctions. Rather than put that out there directly, I think it's best to just not say anything in the FAQ about that. We'll have to respond if we get asked that directly by someone from one of the countries, of course. 

The 'specific domain' question is answered pretty completely in another FAQ answer (what makes a good fellow). A good fellow would be able to apply the answer from that question to the question of whether or not fellows are supposed to be working in a specific domain :stuck_out_tongue: 

Structure of the program is more or less exactly the same copy as the existing questions (what is included in the fellowship).
